version: '2'

services:
  web:
    tty: true
    build: .
    command: npm start -- --host 0.0.0.0 --poll 1000

    volumes:
      - ./src:/code/src
    ports:
      - "4200:4200"
      - "4202:8888"
      - "49153:49153"
