FROM node:16.13-alpine

RUN mkdir /code
WORKDIR /code

COPY package.json /code
RUN npm install

COPY . /code
RUN mkdir /dist
RUN npm run build -- --output-path /dist/

FROM nginx:stable-alpine
COPY --from=0 /dist /dist
COPY apps.conf /etc/nginx/conf.d/
