version: '3.1'

services:
  bigeyedb:
      image: postgres:alpine
      environment:
        POSTGRES_DB: "bigeye"
        POSTGRES_HOST_AUTH_METHOD: "trust"
      network_mode: bridge
      volumes:
        - bigeyedbdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    network_mode: bridge
    depends_on:
      - bigeyedb
    links:
      - bigeyedb
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@codexus.fr
      - PGADMIN_DEFAULT_PASSWORD=changemeplease
      - PGADMIN_LISTEN_PORT=17890
    ports:
      - 17891:17890
    logging:
      driver: none #json-file
    volumes:
      - pgadmindata:/var/lib/pgadmin

  webapi:
    build: .
    tty: true
    command: python serve.py
    network_mode: bridge
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - bigeyedb
    environment:
      - FLASK_APP=bigeye
      - FLASK_ENV=development

volumes:
  bigeyedbdata:
  pgadmindata:
