"""empty message

Revision ID: 0e6ae3b3ec68
Revises: efc084f6919c
Create Date: 2022-01-31 18:08:02.784097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6ae3b3ec68'
down_revision = 'efc084f6919c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('resource', sa.String(length=500), nullable=False))
    op.add_column('challenges', sa.Column('hint', sa.String(length=255), nullable=True))
    op.drop_column('challenges', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('content', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('challenges', 'hint')
    op.drop_column('challenges', 'resource')
    # ### end Alembic commands ###
