"""empty message

Revision ID: 8042d80517c4
Revises: 557da25b46fc
Create Date: 2022-01-31 11:20:48.375636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8042d80517c4'
down_revision = '557da25b46fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_token', sa.String(length=128), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email_token')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
