"""empty message

Revision ID: 8381a85f0dc2
Revises: 8173dca333df
Create Date: 2022-02-01 04:31:37.768227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8381a85f0dc2'
down_revision = '8173dca333df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'points',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'points',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
