name: Build & Publish Front

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-publish:
    name: Build and Publish Front
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Docker Build Image
      run: docker build -t docker.pkg.github.com/astropilot/bigeyes/front -f frontend/Dockerfile.prod frontend/.

    - name: Push Image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u Astropilot --password-stdin docker.pkg.github.com
        docker push docker.pkg.github.com/astropilot/bigeyes/front